# Generated by Django 5.1.6 on 2025-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="banner",
            field=models.ImageField(
                blank=True, default="profile_picture.jpg", upload_to=""
            ),
        ),
    ]
